[package]
name = "redacted"
version = "0.1.0"
edition = "2021"

[dependencies]
reaction-roles = { git = "https://github.com/zayden-bot/reaction-roles.git", branch = "main" }
async-trait = "*"
# chrono = "*"
dotenvy = "*"
# futures = "*"
# lazy_static = "*"
# rand = "*"
# reqwest = { version = "*", features = ["json"] }
# serde = "*"
# serde_json = "1.0.117"
sqlx = { version = "*", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "macros",
    "chrono",
    "uuid",
] }
tokio = { version = "*", default-features = false, features = [
    "macros",
    "rt-multi-thread",
] }
# walkdir = "*"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "current"
# version = "*"
default-features = false
features = [
    "builder",
    "client",
    "collector",
    "gateway",
    "model",
    "utils",
    "rustls_backend",
]
